### ISSUE TITLE
代理地址网络波动

### ISSUE THREAD

**Issue by sun8mota66** [Suxmx/nonebot_plugin_chatgpt_on_qq#1]
![image](https://user-images.githubusercontent.com/48704374/224315665-7e7f9007-993e-45c5-a118-988425a82531.png)

**Comment by Suxmx** [comment]
请问这个是一直出现还是偶尔？

**Comment by Suxmx** [comment]
请问你用的是芝麻的梯子吗，我用的这个告诉我维护了所以我现在也debug不了orz如果是的话应该是维护的问题
![image](https://user-images.githubusercontent.com/33772816/224338329-425ab510-0e95-4045-81c3-58b537c99ee4.png)

**Comment by sun8mota66** [comment]
一直出现，我使用的是动态代理ip，是否与这个有关系

**Comment by Suxmx** [comment]
可能是
