### ISSUE TITLE
请问这个插件的代理要怎么填，是填反向代理的域名吗

### ISSUE THREAD

**Issue by rick23318** [Suxmx/nonebot_plugin_chatgpt_on_qq#10]
如题

**Comment by Suxmx** [comment]
我填的是Window设置中的代理
![image](https://user-images.githubusercontent.com/33772816/229813849-cd1cda47-30a6-449c-8685-cd7ca8e4f1f0.png)

**Comment by rick23318** [comment]
按这样填依然回复如下：‘获取gpt回答失败,访问请求速度过快或是网络波动orz
若反复出现,可尝试使用/chat delete 序号 命令来删除该对话并重新创建’

我对chatgpt账号进行了检查，可以正常聊天，此外在挂了加速器的情况下依旧无法解决这个问题
目前没有什么解决的头绪。请问你遇到过类似的问题嘛

**Comment by Suxmx** [comment]
请检查API额度是否过期 大部分账号的API免费额度在4月1号过期了

**Comment by rick23318** [comment]
刚刚检查过了，并未过期。此外，环境配置如下，应该没有什么问题。并且在程序中得到了正确的加载
![OEU48CLBZ1NWA7YSUW{TCY](https://user-images.githubusercontent.com/110974886/229818321-b4a5ea60-f7ec-4a09-8574-29869c97e9c4.png)
![8{X$JR@V$M$8WSRXIDH}C@2](https://user-images.githubusercontent.com/110974886/229818382-ab8d2df8-1a66-4301-b383-61958418d470.png)

**Comment by rick23318** [comment]
好的，那加qq可以嘛3479292093.
用向日葵？
