### ISSUE TITLE
同名内置预设和自定义预设重复出现

### ISSUE THREAD

**Issue by wangyw15** [Suxmx/nonebot_plugin_chatgpt_on_qq#12]
如题，或许可以让同名的自定义预设覆盖掉内置的？

**Comment by Suxmx** [comment]
没考虑到这种需求orz
![-4b6ffe553649f700](https://user-images.githubusercontent.com/33772816/230838910-9a74d803-dbe8-42a3-b128-8a35727fc72f.gif)

**Comment by Suxmx** [comment]
理论上真的需要的话可以直接删除内置的？

**Comment by wangyw15** [comment]
我觉得大概覆盖掉同名的内置更好？这样可以多给一点自定义的空间（

**Comment by Suxmx** [comment]
考虑的是pip下载插件不会下载github这里的presets文件夹 所以内置了几个 要不我等下改成第一次启动自动创建presets文件夹然后释放基础模板？

**Comment by wangyw15** [comment]
这样应该不错

**Comment by Suxmx** [comment]
改好了 你pip更新一下 或者github直接拉取一下

**Comment by wangyw15** [comment]
现在ok了
