### ISSUE TITLE
为什么/talk的时候不能正常说话

### ISSUE THREAD

**Issue by sushiHHH** [Suxmx/nonebot_plugin_chatgpt_on_qq#15]

**Comment by Suxmx** [comment]
详细点..

**Comment by sushiHHH** [comment]
![QQ图片20230412183559](https://user-images.githubusercontent.com/128274232/231433086-1a422b34-5861-48d9-befb-34a29a006385.png)

**Comment by sushiHHH** [comment]
后面就没有出来了

**Comment by Suxmx** [comment]
close了是解决了吗

**Comment by sushiHHH** [comment]
按错了{哭}，没解决
