### ISSUE TITLE
就是这个不能继续聊天的问题，打/talk的时候没出来

### ISSUE THREAD

**Issue by sushiHHH** [Suxmx/nonebot_plugin_chatgpt_on_qq#16]
![QQ图片20230412183559](https://user-images.githubusercontent.com/128274232/231433878-d6538329-dd77-4e8e-8419-8450a1647bc4.png)

**Comment by Suxmx** [comment]
看看控制台有没有报错

**Comment by sushiHHH** [comment]
![image](https://user-images.githubusercontent.com/128274232/231436472-0b5c85cf-9c81-4369-a245-8a48183831e2.png)
是在这里看吗？

**Comment by Suxmx** [comment]
看chatgpt_on_qq相关的 看你输入/talk后有没有报错

**Comment by sushiHHH** [comment]
![image](https://user-images.githubusercontent.com/128274232/231439332-d324849f-52c3-49f6-8a4a-b5689a286686.png)
启动不了这个了

**Comment by sushiHHH** [comment]
启动不了

**Comment by Suxmx** [comment]
![image](https://user-images.githubusercontent.com/33772816/231440571-1a93c799-3129-41ad-aefb-3f23e32e0e23.png)
虽然.. 但是你开了两个issue没有提供一点信息多少有点浪费时间了
[《提问的智慧》](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md)

**Comment by Suxmx** [comment]
> 看chatgpt_on_qq相关的 看你输入/talk后有没有报错
