### ISSUE TITLE
没有过pydantic v2

### ISSUE THREAD

**Issue by ANGJustinl** [Suxmx/nonebot_plugin_chatgpt_on_qq#31]
恶报😭
https://registry.nonebot.dev/plugin/nonebot-plugin-chatgpt-on-qq:nonebot_plugin_chatgpt_on_qq

**Comment by ANGJustinl** [comment]
config不合v2规范

**Comment by Suxmx** [comment]
我去 这是啥情况

**Comment by ANGJustinl** [comment]
https://github.com/nonebot/nonebot2/releases/tag/v2.2.0

**Comment by Suxmx** [comment]
按照那边改了下
