### ISSUE TITLE
.env中代理声明失效问题

### ISSUE THREAD

**Issue by LiuZhihhxx** [Suxmx/nonebot_plugin_chatgpt_on_qq#6]
抱歉，刚才手滑提交了，还没写完，当然不是直接填的xxx🤣是这样的。
你好，参考readme在.env文件中声明了openai_proxy="x.x.x.x:xxxxx"，启动后会报【获取gpt回答失败,访问请求速度过快或是网络波动orz】的错误，无法正常使用。
将这一行注释掉后，启动时会报配置代理的ERROR，但可以正常使用。
![0BW)VNM1HC$_NHF`)Q{TM 4](https://user-images.githubusercontent.com/73637604/226853007-67b0cd50-30bf-40e4-8cdd-e675cfdde6c4.png)
代理使用了window下clash的TUN模式。
请问这是什么原因？

**Comment by Suxmx** [comment]
你直接吧x.x.x.x:xxxxx填上去股了吗？

**Comment by Suxmx** [comment]
如果不填代理可以用的话那就先不填吧🤣
我等下把那个报错去掉hhhh

**Comment by Suxmx** [comment]
你更新一下试试 已经改了

**Comment by Peins** [comment]
我之前设置proxy没问题。你填错了?本地是http://127.0.0.1:xxxx这样的类似

**Comment by Suxmx** [comment]
看一下ReadMe 把代理改成NoError
