### ISSUE TITLE
第一参数，请输入数字.....

### ISSUE THREAD

**Issue by barryblueice** [Suxmx/nonebot_plugin_chatgpt_on_qq#7]
插件正常启动，机器人也能正常回复，但总是会回复一句第一参数，请输入数字.....

![image](https://user-images.githubusercontent.com/44601454/226987321-32970f13-6501-4538-b432-26b743f0d55a.png)

**Comment by Peins** [comment]
不用加1啊，/talk xxxxxxxxxx就行

**Comment by barryblueice** [comment]
> 不用加1啊，/talk xxxxxxxxxx就行

搞定了……和我那个机器人的某个插件冲突了，删掉那个冲突插件就行
![3QXE IUB_6}ZV1RFKR_MQU5](https://user-images.githubusercontent.com/44601454/227109071-fb8c2196-3f64-45d7-8a3e-720a530d44f2.jpg)

**Comment by Suxmx** [comment]
![53E6517B3F7697DFA8FFE0ABDB0ECC38](https://user-images.githubusercontent.com/33772816/227109350-2158680c-c354-4e29-93af-508d6c998df9.png)
