### ISSUE TITLE
想问下 ，您用的python版本是3.几的呀，3.8   3.9  有很多基本语法不支持，是3.10吗

### ISSUE THREAD

**Issue by yixuan1912** [Suxmx/nonebot_plugin_chatgpt_on_qq#9]

**Comment by Suxmx** [comment]
确实是3.10
不过可能是我写的太不规范了()
因为之前一直写的c#，没有学过Python😭

**Comment by Suxmx** [comment]
大佬有什么想改的欢迎直接发pr

**Comment by yixuan1912** [comment]
在 3.9 以下的版本，变量类型和函数返回类型说明，需要用typing模块，比如 
from typing import List, Union
def _() -> Union[List[str,int]]:
    return [1, '2']

或者在代码最上面导入  from __future__ import annotations 
我没try过，但是似乎是这样

**Comment by Suxmx** [comment]
哦哦 之前有人针对py3.8改过一次类型说明相关的来着

**Comment by yixuan1912** [comment]
在env中添加你的api_key(必选)

这个似乎无效，因为 Config 函数内没使用 get_driver().config.dict() ？

**Comment by Suxmx** [comment]
> 在env中添加你的api_key(必选)
> 
> 这个似乎无效，因为 Config 函数内没使用 get_driver().config.dict() ？
有的 在conversation.py
